// src/components/gamePK.vue
<template>
  <div class="main">
    <div class="route">
      <button class="animated" @click="pkMethod(1)"></button>
      <button class="animated" @click="pkMethod(2)"></button>
      <button class="animated" @click="pkRecord"></button>
      <button class="animated" @click="myAchievements"></button>
    </div>
    <div class="modal" v-show="isShow" @click="isShow = 0">
      <img src="/static/images/tankuang_10.png" ref="img">
      <div class="one_dialog" v-if="dialogShow">
        <router-link to="/train"></router-link>
        <router-link to="/"></router-link>
      </div>
    </div>
  </div>
</template>
<script>

export default {
  data() {
    return {
      user_id: this.$handler.getStorage('user_id'),
      isShow: 0,
      dialogShow: 0
    }
  },
  methods: {
    pkMethod(pkType) {
      this.$Axios.post(this.$baseUrl.base + this.$baseUrl.isPK, {
        userId: this.user_id,
        pkType
      }).then(res => {
        if (res.data.code == 0) {
          if (pkType == 1) {
            this.$router.push('pk')
          } else if (pkType == 2) {
            this.$router.push('setpk')
          }
        } else if (res.data.code == 2) {
          // 训练超过10次
          this.isShow = 1
        } else if (res.data.code == 7) {
          // 没有认证
          this.isShow = 1
          this.dialogShow = 1
          this.$refs.img.src = '/static/images/tankuang.png'
        }
      })
    },
    pkRecord() {
      this.$router.push('pkRecord')
    },
    myAchievements() {
      this.$router.push('myAchievements')
    }
  }
}
</script>

<style lang="scss" scoped>
.main {
  background-image: url(/static/images/gamePK.png);
  position: absolute;
  top: 10vw;
  left: 0;
  width: 100%;
  height: 140vw;
}

.route {
  position: absolute;
  text-align: center;
  top: 40vw;
  button {
    display: inline-block;
    width: 70vw;
    height: 21vw;
    animation-name: fadeInLeft;
    &:first-child {
      background-image: url("/static/images/gamePK_01.png");
    }
    &:nth-child(2) {
      background-image: url("/static/images/gamePK_02.png");
      animation-delay: 0.25s;
    }
    &:nth-child(3) {
      background-image: url("/static/images/gamePK_03.png");
      animation-delay: 0.5s;
    }
    &:nth-child(4) {
      background-image: url("/static/images/gamePK_04.png");
      animation-delay: 0.75s;
    }
  }
}

.one_dialog {
  position: absolute;
  top: 86vw;
  width: 100%;
  text-align: center;
  z-index: 3;
  a {
    display: inline-block;
    width: 30vw;
    height: 10vw;
  }
}
</style>

// src/pages/gamePk.jsx
import React from 'react'
import Axios from 'axios'
import baseUrl from '@/assets/js/baseUrl'
import * as handler from '@/assets/js/handler'
import BgMusic from '@/components/bgMusic'
import TipShow from '@/components/tipShow'

export default class GamePk extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      user_id: handler.getStorage('user_id'),
      tipIsShow: 0,
      dialogIsShow: 0,
      tipImg: require('@img/tankuang_10.png')  // 提示框图片
    }
  }
  componentDidMount() {
    document.title="全民PK"
  }
  pkMethod(pkType) {
    Axios.post(baseUrl.base + baseUrl.isPK, {
      userId: this.state.user_id,
      pkType
    }).then(res => {
      if (res.data.code === 0) {
        if (pkType === 1) {
          handler.handleBtnBgm(() => this.props.history.push('/pk'))
        } else if (pkType === 2) {
          handler.handleBtnBgm(() => this.props.history.push('/setpk'))
        }
      } else if (res.data.code === 2) {
        // 训练超过10次
        this.setState({tipIsShow: 1})
      } else if (res.data.code === 7) {
        // 没有认证
        this.setState({
          tipIsShow: 1,
          dialogIsShow: 1,
          tipImg: require('@img/tankuang.png')
        })
      }
    })
  }
  pkRecord = () => {
    handler.handleBtnBgm(() => this.props.history.push('/pkRecord'))
  }
  myAchievements = () => {
    handler.handleBtnBgm(() => this.props.history.push({ pathname: '/myAchievements/' + this.state.user_id }))
  }
  render() {
    return (
      <div className='main' id='gamePk'>
        <BgMusic />
        <div className='route _center'>
          <button className='animated' onClick={() => this.pkMethod(1)}></button>
          <button className='animated' onClick={() => this.pkMethod(2)}></button>
          <button className='animated' onClick={this.pkRecord}></button>
          <button className='animated' onClick={this.myAchievements}></button>
        </div>
        <TipShow
          tipIsShow={this.state.tipIsShow}
          tipImg={this.state.tipImg}
          dialogIsShow={this.state.dialogIsShow}
        />
      </div>
    )
  }
}
