// src/components/subject.vue
<template>
  <div class="main">
    <audio src="~music/time_out.mp3" id="timeOut" loop="loop" :autoplay="autoplay"></audio>
    <audio src="~music/select_click.mp3" id="selectClick"></audio>
    <div class="time">{{ time }}</div>
    <ul class="scrollbar">
      <li v-for="(value, key) in list" :key="key">
        <div v-if="key == question_index">
          <div class="current">{{key + 1}}/{{list.length}}</div>
          <div class="title">{{ value.question_content }}</div>
          <div class="option_a" v-if="value.option_a != ''" @click="doAnswer(1)">
            <img src="~img/no_select.png" ref="img">
            <span ref="text">{{ value.option_a }}</span>
          </div>
          <div class="option_b" v-if="value.option_b != ''" @click="doAnswer(2)">
            <img src="~img/no_select.png" ref="img">
            <span ref="text">{{ value.option_b }}</span>
          </div>
          <div class="option_c" v-if="value.option_c != ''" @click="doAnswer(3)">
            <img src="~img/no_select.png" ref="img">
            <span ref="text">{{ value.option_c }}</span>
          </div>
          <div class="option_d" v-if="value.option_d != ''" @click="doAnswer(4)">
            <img src="~img/no_select.png" ref="img">
            <span ref="text">{{ value.option_d }}</span>
          </div>
        </div>
      </li>
    </ul>
    <div class="ad" v-if="ad_isShow">
      <img :src="adInfo_img">
      <span v-text="adInfo_value"></span>
    </div>
  </div>
</template>
<script>
import common from './mixins/common.js'
export default {
  mixins: [common],
  data() {
    return {
      list: [],
      time: 20,  // 倒计时
      timer: '',  // 计时器id
      question_index: 0,   // 当前第几题
      isClick: false,  // 禁止重复点击
      ad_isShow: 0,  // 是否显示广告
      adInfo_img: require('img/ad_logo01.png'),   // 广告图标
      adInfo_value: '强效促成骨 提高骨质量 预防再骨折',  // 广告标语
      score: 0,  // 得分
      correct: 0  // 正确题目数量
    }
  },
  mounted() {
    this.init()
  },
  destroyed() {
    clearInterval(this.timer)
  },
  methods: {
    init() {
      this.$Axios.post(this.$baseUrl.base + this.$baseUrl.findAllSubject, {
        userId: this.user_id,
        levelId: this.$route.params.levelId
      }).then(res => {
        if (res.data.code == 0) {
          this.list = res.data.body
          this.intervalHandler()
          this.showAdInfo()
        } else {
          this.backTrain()
        }
      })
    },
    showAdInfo() {
      // 显示广告
      if (this.list[this.question_index].ad_info != null) {
        this.ad_isShow = 1
        this.adInfo_img = this.list[this.question_index].ad_info.ad_img
        this.adInfo_value = this.list[this.question_index].ad_info.ad_content
      }
    },
    intervalHandler() {
      this.timer = setInterval(() => {
        this.time--
        if (this.time < 1) {
          // 未作答时默认答题选项
          this.sumbit(0)
        }
      }, 1000)
    },
    doAnswer(answerOption) {
      // answerOption: 玩家回答的选项
      if (this.isClick) return  // 防止重复点击
      if (this.autoplay) {
        this.$handler.btnPlay('selectClick')
      }
      this.isClick = true
      clearInterval(this.timer)
      if (this.list[this.question_index].option_answer == answerOption) {
        this.$refs.img[answerOption - 1].src = require('img/right.png')
        this.$refs.text[answerOption - 1].style.color = '#2661b4'
        this.correct++
        this.score += this.list[this.question_index].level_score
      } else {
        this.$refs.img[answerOption - 1].src = require('img/wrong.png')
        this.$refs.text[answerOption - 1].style.color = '#fd8900'
      }
      setTimeout(() => {
        this.sumbit(answerOption)
        this.isClick = false
        this.intervalHandler()
      }, 3000)
    },
    sumbit(answerOption) {
      this.$Axios.post(this.$baseUrl.base + this.$baseUrl.toanswer, {
        userId: this.user_id,  // 玩家id
        answerOption: answerOption,  // 玩家回答的选项
        questionId: this.list[this.question_index].question_id  // 题目id
      }).then((res) => {
        // 全部题目答完后
        if (this.question_index + 1 == this.list.length) {
          clearInterval(this.timer)
          this.$router.push({
            name: 'finishTraining',
            query: {
              user_id: this.user_id,
              score: this.score,
              correct: this.correct
            }
          })
        } else {
          this.time = 20
          this.question_index++
          this.showAdInfo()
        }
      })
    },
    backTrain() {
      this.$router.push('train')
    }
  }
}
</script>

<style lang="scss" scoped>
$color: #275fb2;
.main {
  background-image: url(~img/subject.png);
  position: absolute;
  top: 5vw;
  left: 0;
  width: 100%;
  height: 136vw;
}
.time {
  position: absolute;
  left: 39vw;
  top: 13vw;
  width: 22vw;
  height: 22vw;
  line-height: 22vw;
  text-align: center;
  color: #fff;
  font-size: 11vw;
  font-weight: bold;
  font-family: Arial;
}
ul {
  position: absolute;
  width: 70vw;
  height: 80vw;
  overflow: auto;
  left: 15vw;
  top: 36vw;
  font-weight: bold;
  li > div {
    opacity: 0;
    animation: fadeIn 1s 0.2s forwards;
  }
  .current {
    font-size: 5vw;
    color: $color;
  }
  .title {
    font-size: 15px;
    color: $color;
  }
  div[class^="option"] {
    margin-top: 2.5vw;
  }
  img {
    width: 8vw;
    height: 8vw;
    vertical-align: top;
    transform: translateY(-2px);
  }
  span {
    display: inline-block;
    width: 59vw;
    font-size: 14px;
  }
}
.ad {
  position: absolute;
  background-image: url(~img/foot.png);
  height: 8vw;
  width: 80vw;
  top: 138vw;
  left: 10vw;
  img {
    position: absolute;
    width: 18vw;
    left: 1.5vw;
    top: 1.5vw;
  }
  span {
    position: absolute;
    display: inline-block;
    left: 28vw;
    width: 50vw;
    font-size: 12px;
    font-weight: 600;
    color: #fff;
    top: 1.2vw;
  }
}
</style>

// src/pages/subject/subject.jsx
import React from 'react'
import Axios from 'axios'
import Option from '../../components/option/option'
import baseUrl from '@/assets/js/baseUrl'
import handler from '@/assets/js/handler'
import './subject.scss'

export default class Subject extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      user_id: handler.getStorage('user_id'),
      list: [],
      time: 20,  // 倒计时
      // timerID: '',  // 计时器id
      question_index: 0,   // 当前第几题
      isClick: false,  // 禁止重复点击
      ad_isShow: 0,  // 是否显示广告
      adInfo_img: require('@img/ad_logo01.png'),   // 广告图标
      adInfo_value: '强效促成骨 提高骨质量 预防再骨折',  // 广告标语
      score: 0,  // 得分
      correct: 0  // 正确题目数量
    }
  }
  componentDidMount() {
    console.log(this.props.match.params)
    Axios.post(baseUrl.base + baseUrl.findAllSubject, {
      userId: this.state.user_id,
      levelId: this.props.match.params.levelId
    }).then(res => {
      if (res.data.code === 0) {
        this.setState({
          list: res.data.body
        })
        this.intervalHandler()
      }
    })
  }
  componentWillUnmount() {
    clearInterval(this.timerID)
  }
  intervalHandler() {
    this.timerID = setInterval(() => {
      this.setState({ time: this.state.time - 1 })
      if (this.state.time < 1) {
        // 未作答时默认答题选项
        this.sumbit(0)
      }
    }, 1000)
  }
  doAnswer(answerOption /*玩家回答的选项*/) {
    if (this.state.isClick) return  // 防止重复点击
    clearInterval(this.timerID)
    // if (this.autoplay) {
    //   this.$handler.btnPlay('selectClick')
    // }
    this.setState({ isClick: true })
    if (this.state.list[this.state.question_index].option_answer == answerOption) {
      this.refs.option.children[answerOption - 1].children[0].src = require('@img/right.png')
      this.refs.option.children[answerOption - 1].children[1].style.color = '#2661b4'
      this.setState({
        correct: this.state.correct + 1,
        score: this.state.score + this.state.list[this.state.question_index].level_score
      })
    } else {
      this.refs.option.children[answerOption - 1].children[0].src = require('@img/wrong.png')
      this.refs.option.children[answerOption - 1].children[1].style.color = '#fd8900'
    }
    setTimeout(() => {
      this.sumbit(answerOption)
      this.setState({ isClick: false })
      this.intervalHandler()
    }, 3000)
  }
  sumbit(answerOption) {
    Axios.post(baseUrl.base + baseUrl.toanswer, {
      userId: this.state.user_id,  // 玩家id
      answerOption: answerOption,  // 玩家回答的选项
      questionId: this.state.list[this.state.question_index].question_id  // 题目id
    }).then(() => {
      // 全部题目答完后
      if (this.state.question_index + 1 == this.state.list.length) {
        clearInterval(this.timerID)
        // this.$router.push({
        //   name: 'finishTraining',
        //   query: {
        //     user_id: this.user_id,
        //     score: this.score,
        //     correct: this.correct
        //   }
        // })
      } else {
        this.setState({
          time: 20,
          question_index: this.state.question_index + 1
        })
        // this.showAdInfo()
      }
    })
  }
  render() {
    return (
      <div className='main subject'>
        <div className='time'>{this.state.time}</div>
        <ul className='scrollbar'>
          {this.state.list.map((ele, i, arr) => {
            return i === this.state.question_index ? (
              <li key={i}>
                <div className='current'>{i + 1}/{arr.length}</div>
                <div className='title'>{ele.question_content}</div>
                <ul ref='option'>
                  <Option doAnswer={() => this.doAnswer(1)} img={require('@img/no_select.png')} text={ele.option_a}></Option>
                  <Option doAnswer={() => this.doAnswer(2)} img={require('@img/no_select.png')} text={ele.option_b}></Option>
                  <Option doAnswer={() => this.doAnswer(3)} img={require('@img/no_select.png')} text={ele.option_c}></Option>
                  <Option doAnswer={() => this.doAnswer(4)} img={require('@img/no_select.png')} text={ele.option_d}></Option>
                </ul>
              </li>
            ) : ''
          })}
        </ul>
      </div>
    )
  }
}
