// src/components/bgMusic.vue
<template>
  <div>
    <audio src="~music/index_bg.mp3" loop id="myAudio" :autoplay="isAutoPlay"></audio>
    <audio src="~music/button.mp3" id="buttonPlay"></audio>
    <div class="music_btn" :class="{play: isAutoPlay, pause: !isAutoPlay}" :style='{ top: top }' @click="audioControl"></div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      isAutoPlay: JSON.parse(window.sessionStorage.getItem('isAutoPlay'))  // 是否自动播放音乐
    }
  },
  props: {
    top: String
  },
  methods: {
    audioControl() {
      this.isAutoPlay = !this.isAutoPlay
      this.$handler.handleMusic("myAudio")
      window.sessionStorage.setItem("isAutoPlay", this.isAutoPlay)
    }
  }
};
</script>

// src/components/bgMusic.jsx
import React from 'react'
import * as handler from '../assets/js/handler'

export default class BgMusic extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      isAutoPlay: JSON.parse(window.sessionStorage.getItem('isAutoPlay')),
    }
  }
  audioControl = () => {
    this.setState({
      isAutoPlay: !this.state.isAutoPlay
    }, () => {
      handler.handleMusic('myAudio')
      window.sessionStorage.setItem('isAutoPlay', this.state.isAutoPlay)
    })
  }
  render() {
    return (
      <div>
        <audio src={require('@music/index_bg.mp3')} loop id="myAudio" autoPlay={this.state.isAutoPlay}></audio>
        <audio src={require('@music/button.mp3')} id="buttonPlay"></audio>
        <div className={'music_btn ' + (this.state.isAutoPlay ? 'play' : 'pause')} onClick={this.audioControl}></div>
      </div>
    )
  }
}
